openapi: 3.0.0
info:
  title: Nabil's Music API
  description: API based on the FMA dataset
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /:
    get:
      summary: Home
      description: Welcome message for the API.
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
              example: Welcome to Nabil's Music API based on FMA dataset

  /track/{track_id}:
    get:
      summary: Get Track
      description: Retrieve details of a specific track by its ID.
      parameters:
        - name: track_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the track to retrieve.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  track_id:
                    type: integer
                  track_title:
                    type: string
                  artist_name:
                    type: string
                  genre_handle:
                    type: string
                  genre_id:
                    type: integer
                  album_handle:
                    type: string
        '404':
          description: Track not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /genre/{genre_id}:
    get:
      summary: Get Genre
      description: Retrieve details of a specific genre by its ID.
      parameters:
        - name: genre_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the genre to retrieve.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  genre_id:
                    type: integer
                  genre_handle:
                    type: string
                  other_properties:
                    type: string
        '404':
          description: Genre not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /feature/{track_id}:
    get:
      summary: Get Feature
      description: Retrieve features of a specific track by its ID.
      parameters:
        - name: track_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the track to retrieve features for.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  track_id:
                    type: integer
                  track_title:
                    type: string
                  artist_name:
                    type: string
                  genre_handle:
                    type: string
                  genre_id:
                    type: integer
                  acousticness:
                    type: number
                  danceability:
                    type: number
                  energy:
                    type: number
                  instrumentalness:
                    type: number
                  liveness:
                    type: number
                  speechiness:
                    type: number
                  tempo:
                    type: number
                  valence:
                    type: number
        '404':
          description: Feature not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
